### ISSUE TITLE
Some parts of this utility require Python >= 3.10

### ISSUE THREAD

**Issue by abraha2d** [natthawk/TMOHS1-Root-Utility#1]
I think mainly this new `match` syntax: https://github.com/natthawk/TMOHS1-Root-Utility/blob/main/utils.py#L201

```
$ python ./rootScript.py 
Traceback (most recent call last):
  File "./rootScript.py", line 22, in <module>
    from utils import TelnetConnection,chooseAction,chPwdFlag
  File "./utils.py", line 201
    match choice:
          ^
SyntaxError: invalid syntax
```

```
$ python --version
Python 3.8.10
```

Would recommend either updating the README to specify the requirement for Python >= 3.10, or using something that works with older Python version (Ubuntu 20.04 still doesn't have Python 3.10 in the main repos).

EIther way, thank you for the work put into this! Other than this it worked well for me.

**Comment by natthawk** [comment]
You're right, good catch. Give me a few and I'll fix this!

**Comment by natthawk** [comment]
Fixed with commit https://github.com/natthawk/TMOHS1-Root-Utility/commit/90cb49a14ad178a3b53a61a747e810733b6a6325. Thanks again for letting me know!
