### ISSUE TITLE
Hotspot rejecting request. Double check the password

### ISSUE THREAD

**Issue by poltergiest** [natthawk/TMOHS1-Root-Utility#2]
Software Version: TMOHS1_0.04.18
Hardware Version: 89527_1_11
Python 3.10.1

Just got this, took out the sim and connected to my arch linux box. Change the admin password to something else and tried the python script.
Keep getting: Error: The hotspot rejected our request. Double check the password and try again.

Enter your weblogin password:
Sending the authentication request. . .
# /usr/lib/python3.10/__pycache__/netrc.cpython-310.pyc matches /usr/lib/python3.10/netrc.py
# code object from '/usr/lib/python3.10/__pycache__/netrc.cpython-310.pyc'
# /usr/lib/python3.10/__pycache__/shlex.cpython-310.pyc matches /usr/lib/python3.10/shlex.py
# code object from '/usr/lib/python3.10/__pycache__/shlex.cpython-310.pyc'
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x7f9b4c76fd00>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x7f9b4c76faf0>
Error: The hotspot rejected our request. Double check the password and try again.

**Comment by natthawk** [comment]
Hmm... This is pretty weird. It seems like something may be wrong with your Python environment, as I'm running on Arch (technically EndeavorOS) Python 3.10.1 without issue. I just updated the script with a verbose mode (-v) through commit https://github.com/natthawk/TMOHS1-Root-Utility/commit/33833c9ad9e78e8de5458ea035cf06472ebdb334, so do you mind running the script again in verbose mode and pasting whatever the output after "Sending the authentication request" ends up being? That will help me figure this out.

**Comment by poltergiest** [comment]
made sure pip requirements are met, they did not add anything.  
The password is correct, I can log into the webadmin screen. Even changed to make sure I did not fat finger it.
Also put it the script so I can see its correct got the exact same error both ways.

So ran it again;
Encrypting the login payload with key "abcdefghijklmn12" [yes, that's really the key]. . .
Sending the authentication request. . .

Error: The hotspot rejected our login attempt with error 3 (likely incorrect password).

Error details: 
        Response status code: 200
        Response data: {'result': '3', 'ip': '0'}

**Comment by spotalertzero** [comment]
I tried the same in windows with the same error
All the pip packages was installed, additionally enabled telnet in windows, connected with USB

C:\Users\Downloads\Python>py rootScript.py -v

Verbose mode enabled.

Enter your weblogin password:
Encrypting the login payload with key "abcdefghijklmn12" [yes, that's really the key]. . .
Sending the authentication request. . .

Error: The hotspot rejected our login attempt with error 3 (likely incorrect password).

Error details:
        Response status code: 200
        Response data: {'result': '3', 'ip': '0'}

Please let me know if you need any more inputs, would love to debug the script

**Comment by natthawk** [comment]
Okay, I found the issue. Really sorry that it has taken me so long! I've been super busy with my classes lately and have not had time to debug the script. In the process of troubleshooting, though, I found a few other bugs as well that I want to fix. Good news is that I should have a fixed version out later today with a full explanation of what was causing this issue once I verify that my fixes work properly.

**Comment by natthawk** [comment]
Fixed with commit https://github.com/natthawk/TMOHS1-Root-Utility/commit/50371b2c8d14ec88f7a2c17e608214efaac5b7d5. 

The issue was that some weblogin passwords encrypt to base64 strings that include the `/` character. `urllib.parse.urlencode()` was turning them into `%2F` in the authentication request, which causes the hotspot to reject the request. I hadn't originally considered escaping this character because the password I happened to be using didn't encrypt to a base64 string with a `/`. 

I also fixed a few small things and reworked the persistent ADB enabling script. 

I am closing this issue, but please let me know if this new version doesn't solve the problem. Thanks again for letting me know about it!

**Comment by spotalertzero** [comment]
Also on another note from another user, tried accessing the hidden page (http://192.168.0.1/#/FotaHide) but the page dont have any other option for sim unlock.

Reference from the below link
https://rotar.tk/t-mobile-mobile-hotspot-tmohs1/

Hope you reach sim unlock in some point of time, if possible please include me in your testing and support.

Thanks

**Comment by natthawk** [comment]
Yes, FotaHide is exclusively for editing firmware update settings and isn't of any use for SIM unlocking the hotspot unfortunately. Also, the above issue does appear to be something new, but I may not have time to troubleshoot anytime soon as a I've been fairly busy lately. I do not have the script set up on a Windows machine and have exclusively run it on Linux so far, which is really all that I am "officially" supporting at the moment. In the meantime, you can run the script from a bootable Linux USB and that should (hopefully) work without issue.

**Comment by spotalertzero** [comment]
I can try running in VMware workstation, Please let me know the os and
version you are using.

Thanks
