### ISSUE TITLE
Working on Windows 11 

### ISSUE THREAD

**Issue by pspfreak** [natthawk/TMOHS1-Root-Utility#3]
Just figured I'd let you know it works on Windows 11 running with Python 3.10.2, worked first try no problems!

**Comment by natthawk** [comment]
Great, thanks for the info! And just to verify--It doesn't break when you try it a second time, right? I've received a report here: https://github.com/natthawk/TMOHS1-Root-Utility/issues/2#issuecomment-1035840038 of this happening on Windows and I want to determine if it's a widespread issue.

**Comment by pspfreak** [comment]
Apologies for not getting back earlier, yes it ran just fine a second time for me, no problems there.
