### ISSUE TITLE
Accidentally overwrote index.html

### ISSUE THREAD

**Issue by ruupoo488** [natthawk/TMOHS1-Root-Utility#9]
I did a pretty stupid goof and overwrote index.html for the webserver. Does anyone have a backup?

**Comment by mtfurlan** [comment]
My `/WEBSERVER/www/index.html` is:
```html
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=format-detection content="telephone=no"><title>MIFI</title><link href=static/css/app.5f283b77.css rel=preload as=style><link href=static/css/chunk-vendors.55852678.css rel=preload as=style><link href=static/js/app.cf45a03c.js rel=preload as=script><link href=static/js/chunk-vendors.b06997a3.js rel=preload as=script><link href=static/css/chunk-vendors.55852678.css rel=stylesheet><link href=static/css/app.5f283b77.css rel=stylesheet></head><body><div id=app></div><script src=static/js/chunk-vendors.b06997a3.js></script><script src=static/js/app.cf45a03c.js></script></body></html>
```

**Comment by ruupoo488** [comment]
> My `/WEBSERVER/www/index.html` is:
> 
> ```
> <!DOCTYPE html><html lang=en><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=viewport content="width=device-width,initial-scale=1"><meta name=format-detection content="telephone=no"><title>MIFI</title><link href=static/css/app.5f283b77.css rel=preload as=style><link href=static/css/chunk-vendors.55852678.css rel=preload as=style><link href=static/js/app.cf45a03c.js rel=preload as=script><link href=static/js/chunk-vendors.b06997a3.js rel=preload as=script><link href=static/css/chunk-vendors.55852678.css rel=stylesheet><link href=static/css/app.5f283b77.css rel=stylesheet></head><body><div id=app></div><script src=static/js/chunk-vendors.b06997a3.js></script><script src=static/js/app.cf45a03c.js></script></body></html>
> ```

Thank you!!! this worked for me!
